-- Adds core gamification schema: points/levels, achievements, streaks, challenges
-- NOTE: Supabase RLS policies will be added in a follow-up migration.

-- 1. Points & Levels -------------------------------------------------------
create table if not exists public.user_points (
  user_id uuid primary key references auth.users (id) on delete cascade,
  total_points integer not null default 0,
  level integer not null default 1,
  updated_at timestamptz not null default now()
);

-- 2. Achievements -----------------------------------------------------------
create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  points integer not null default 0,
  icon text,               -- store relative path or icon name
  created_at timestamptz not null default now()
);

create table if not exists public.user_achievements (
  user_id uuid references auth.users(id) on delete cascade,
  achievement_id bigint references public.achievements(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key (user_id, achievement_id)
);

-- 3. Daily Activity / Streaks ----------------------------------------------
create table if not exists public.daily_activity (
  user_id uuid references auth.users(id) on delete cascade,
  activity_date date not null,
  activity_type text not null,  -- e.g. expense_logged, bill_paid, login
  primary key (user_id, activity_date, activity_type)
);

-- 4. Challenges -------------------------------------------------------------
create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  target_value numeric,          -- eg amount to save
  metric text,                   -- eg expense_amount, debt_paid
  duration_days integer,         -- eg 7 days, 30 days
  points_reward integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.user_challenges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  challenge_id bigint references public.challenges(id) on delete cascade,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  progress numeric default 0,
  status text not null default 'in_progress'  -- in_progress, completed, failed
);

-- 5. Helper function to add points -----------------------------------------
-- Calculates streak inside client, but we also add a helper to compute current streak.

-- Simple implementation; can be replaced with more complex logic later.
create or replace function public.award_points(p_user_id uuid, p_points integer)
returns void language plpgsql as $$
begin
  insert into public.user_points (user_id, total_points)
  values (p_user_id, p_points)
  on conflict (user_id) do update
    set total_points = public.user_points.total_points + p_points,
        updated_at = now();
end;
$$;

-- 6. Basic RLS setup (disabled by default – enable if project enforces RLS) --
-- alter table public.user_points enable row level security;
-- alter table public.user_achievements enable row level security;
-- alter table public.daily_activity enable row level security;
-- alter table public.user_challenges enable row level security;
-- Policy definitions will follow best practices in subsequent migrations.

-- 6. Function to calculate current streak -----------------------------------
create or replace function public.get_current_streak(p_user_id uuid)
returns integer language plpgsql as $$
declare
  streak integer := 0;
  current_day date := current_date;
begin
  loop
    exit when not exists (
      select 1 from public.daily_activity
      where user_id = p_user_id and activity_date = current_day);
    streak := streak + 1;
    current_day := current_day - interval '1 day';
  end loop;
  return streak;
end;
$$;

-- END OF MIGRATION
