-- GAMIFICATION SYSTEM: POINTS, ACHIEVEMENTS, STREAKS, CHALLENGES ---------------------

-- 1. Points & Levels ------------------------------------------------------------------
create table if not exists public.user_points (
  user_id uuid primary key references auth.users (id) on delete cascade,
  total_points integer not null default 0,
  level integer not null default 1,
  updated_at timestamptz not null default now()
);

-- 2. Achievements ---------------------------------------------------------------------
create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  points integer not null default 0,
  icon text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_achievements (
  user_id uuid references auth.users(id) on delete cascade,
  achievement_id bigint references public.achievements(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key (user_id, achievement_id)
);

-- 3. Daily Activity / Streaks ---------------------------------------------------------
create table if not exists public.daily_activity (
  user_id uuid references auth.users(id) on delete cascade,
  activity_date date not null,
  activity_type text not null,
  primary key (user_id, activity_date, activity_type)
);

-- 4. Challenges -----------------------------------------------------------------------
create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  target_value numeric,
  metric text,
  duration_days integer,
  points_reward integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.user_challenges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  challenge_id bigint references public.challenges(id) on delete cascade,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  progress numeric default 0,
  status text not null default 'in_progress'
);

-- 5. Helper Functions -----------------------------------------------------------------

create or replace function public.award_points(p_user_id uuid, p_points integer)
returns void language plpgsql as $$
begin
  insert into public.user_points (user_id, total_points)
  values (p_user_id, p_points)
  on conflict (user_id) do update
    set total_points = public.user_points.total_points + p_points,
        updated_at = now();
end;
$$;

drop function if exists public.record_daily_activity(uuid, text);

create or replace function public.record_daily_activity(p_user_id uuid, p_activity_type text)
returns void language plpgsql as $$
begin
  insert into public.daily_activity (user_id, activity_date, activity_type)
  values (p_user_id, current_date, p_activity_type)
  on conflict do nothing;
end;
$$;

create or replace function public.get_current_streak(p_user_id uuid)
returns integer language plpgsql as $$
declare
  streak integer := 0;
  current_day date := current_date;
begin
  loop
    exit when not exists (
      select 1 from public.daily_activity
      where user_id = p_user_id and activity_date = current_day);
    streak := streak + 1;
    current_day := current_day - interval '1 day';
  end loop;
  return streak;
end;
$$;

-- 6. Sample Data: Achievements & Challenges -------------------------------------------

insert into public.achievements (name, description, points, icon)
values
 ('Income Earner', 'Recorded first income entry', 50, '/icons/achv_first_income.svg'),
 ('Debt Destroyer', 'Made first debt payment', 75, '/icons/achv_first_debt_payment.svg'),
 ('Goal Getter', 'Completed first financial goal milestone', 100, '/icons/achv_goal_milestone.svg'),
 ('Subscription Slayer', 'Cancelled a recurring subscription', 80, '/icons/achv_subscription_cancel.svg'),
 ('High Roller', 'Logged an expense over $1000', 120, '/icons/achv_high_expense.svg'),
 ('Net Worth Hero', 'Reached a net worth of $10,000', 300, '/icons/achv_networth_10k.svg'),
 ('Consistency Champ', 'Logged in 7 days in a row', 150, '/icons/achv_7_day_streak.svg'),
 ('Budget Boss', 'Created and used 3 budgets', 90, '/icons/achv_budget_boss.svg'),
 ('Bill Buster', 'Paid all bills on time for a month', 100, '/icons/achv_bill_buster.svg'),
 ('Investor Alert', 'Logged your first investment', 60, '/icons/achv_first_investment.svg');

insert into public.challenges (title, description, target_value, metric, duration_days, points_reward)
values
 ('Log 20 Expenses', 'Track 20 expenses this week', 20, 'expense_count', 7, 200),
 ('Pay $500 Debt', 'Reduce total debt by $500 this month', 500, 'debt_paid', 30, 300),
 ('Save $5000', 'Increase net worth by $5,000 in 6 months', 5000, 'net_worth_increase', 180, 1000),
 ('Streak Starter', 'Use the app every day for 5 days', 5, 'daily_login', 5, 150),
 ('Bill Master', 'Pay at least 5 different bills this month', 5, 'bills_paid', 30, 250),
 ('Subscription Cleanse', 'Cancel 2 or more subscriptions this month', 2, 'subscriptions_cancelled', 30, 200),
 ('Goal Tracker', 'Update goal progress at least 4 times this month', 4, 'goal_updates', 30, 180),
 ('Track It All', 'Log income, expense, bill, and debt in one week', 4, 'unique_activity_types', 7, 250);

-- 7. Triggers for Gamification Events -------------------------------------------------

-- Income
create or replace function public.income_gamification()
returns trigger language plpgsql as $$
begin
  perform public.award_points(NEW.user_id, 10);
  perform public.record_daily_activity(NEW.user_id, 'income_recorded');
  return NEW;
end;
$$;

DO $$
BEGIN
  IF EXISTS (select 1 from information_schema.tables where table_name = 'incomes') THEN
    IF EXISTS (select 1 from pg_trigger where tgname = 'trg_income_gamification') THEN
      drop trigger trg_income_gamification on public.incomes;
    END IF;
    create trigger trg_income_gamification
      after insert on public.incomes
      for each row execute procedure public.income_gamification();
  END IF;
END $$;

-- Debt Payments (via `debts` table update)
create or replace function public.debt_payment_gamification()
returns trigger language plpgsql as $$
begin
  if NEW.last_payment_amount is distinct from OLD.last_payment_amount and NEW.last_payment_amount is not null then
    perform public.award_points(NEW.user_id, floor(NEW.last_payment_amount / 10));
    perform public.record_daily_activity(NEW.user_id, 'debt_payment');
  end if;
  return NEW;
end;
$$;

DO $$
BEGIN
  IF EXISTS (select 1 from information_schema.tables where table_name = 'debts') THEN
    IF EXISTS (select 1 from pg_trigger where tgname = 'trg_debt_payment_gamification') THEN
      drop trigger trg_debt_payment_gamification on public.debts;
    END IF;
    create trigger trg_debt_payment_gamification
      after update on public.debts
      for each row execute procedure public.debt_payment_gamification();
  END IF;
END $$;

-- Subscription Cancel
create or replace function public.subscription_cancel_gamification()
returns trigger language plpgsql as $$
begin
  if TG_OP = 'UPDATE' and OLD.active = true and NEW.active = false then
    perform public.award_points(NEW.user_id, 50);
    perform public.record_daily_activity(NEW.user_id, 'subscription_cancelled');
  end if;
  return NEW;
end;
$$;

DO $$
BEGIN
  IF EXISTS (select 1 from information_schema.tables where table_name = 'subscriptions') THEN
    IF EXISTS (select 1 from pg_trigger where tgname = 'trg_subscription_cancel_gamification') THEN
      drop trigger trg_subscription_cancel_gamification on public.subscriptions;
    END IF;
    create trigger trg_subscription_cancel_gamification
      after update on public.subscriptions
      for each row execute procedure public.subscription_cancel_gamification();
  END IF;
END $$;

-- Goal Milestone
create or replace function public.goal_milestone_gamification()
returns trigger language plpgsql as $$
begin
  if NEW.completed = true and OLD.completed is distinct from true then
    perform public.award_points(NEW.user_id, 100);
    perform public.record_daily_activity(NEW.user_id, 'goal_milestone');
  end if;
  return NEW;
end;
$$;

DO $$
BEGIN
  IF EXISTS (select 1 from information_schema.tables where table_name = 'goal_milestones') THEN
    IF EXISTS (select 1 from pg_trigger where tgname = 'trg_goal_milestone_gamification') THEN
      drop trigger trg_goal_milestone_gamification on public.goal_milestones;
    END IF;
    create trigger trg_goal_milestone_gamification
      after update on public.goal_milestones
      for each row execute procedure public.goal_milestone_gamification();
  END IF;
END $$;

-- Expense Logging
create or replace function public.expense_gamification()
returns trigger language plpgsql as $$
begin
  perform public.award_points(NEW.user_id, 5);
  perform public.record_daily_activity(NEW.user_id, 'expense_logged');
  return NEW;
end;
$$;

DO $$
BEGIN
  IF EXISTS (select 1 from information_schema.tables where table_name = 'expenses') THEN
    IF EXISTS (select 1 from pg_trigger where tgname = 'trg_expense_gamification') THEN
      drop trigger trg_expense_gamification on public.expenses;
    END IF;
    create trigger trg_expense_gamification
      after insert on public.expenses
      for each row execute procedure public.expense_gamification();
  END IF;
END $$;

-- Bill Payment
create or replace function public.bill_payment_gamification()
returns trigger language plpgsql as $$
begin
  perform public.award_points(NEW.user_id, 10);
  perform public.record_daily_activity(NEW.user_id, 'bill_paid');
  return NEW;
end;
$$;

DO $$
BEGIN
  IF EXISTS (select 1 from information_schema.tables where table_name = 'bill_payments') THEN
    IF EXISTS (select 1 from pg_trigger where tgname = 'trg_bill_payment_gamification') THEN
      drop trigger trg_bill_payment_gamification on public.bill_payments;
    END IF;
    create trigger trg_bill_payment_gamification
      after insert on public.bill_payments
      for each row execute procedure public.bill_payment_gamification();
  END IF;
END $$;

-- END OF GAMIFICATION MIGRATION ------------------------------------------------------
