import type { BudgetTemplate } from "@/types/budget"

export const LIFESTYLE_TEMPLATES: BudgetTemplate[] = [
  // --- World Travel (Enhanced) ---
  {
    id: "world-travel",
    name: "World Travel",
    description: "12-month world travel budget",
    type: "zero-based",
    categories: [
      {
        name: "Transportation",
        percentage: 35,
        amount: 12250,
        tip: "Flights, trains, buses, taxis for global travel.",
        icon: "plane",
        color: "#63B3ED",
        subcategories: [
          { name: "Flights", percentage: 20, amount: 7000, tip: "International and domestic flights.", icon: "plane", color: "#63B3ED" },
          { name: "Local Transport", percentage: 10, amount: 3500, tip: "Buses, trains, taxis, car rentals.", icon: "bus", color: "#F56565" },
          { name: "Travel Insurance", percentage: 5, amount: 1750, tip: "Comprehensive travel insurance.", icon: "shield-alt", color: "#A0AEC0" },
        ],
      },
      {
        name: "Accommodation",
        percentage: 30,
        amount: 10500,
        tip: "Hotels, hostels, Airbnb, or rentals.",
        icon: "bed",
        color: "#F6AD55",
        subcategories: [
          { name: "Hotels", percentage: 15, amount: 5250, tip: "Hotel stays.", icon: "bed", color: "#F6AD55" },
          { name: "Hostels", percentage: 10, amount: 3500, tip: "Hostel stays for budget travel.", icon: "home", color: "#ED8936" },
          { name: "Airbnb", percentage: 5, amount: 1750, tip: "Short-term rentals.", icon: "home", color: "#4F8EF7" },
        ],
      },
      {
        name: "Activities",
        percentage: 20,
        amount: 7000,
        tip: "Tours, attractions, cultural events.",
        icon: "map-marked-alt",
        color: "#68D391",
        subcategories: [
          { name: "Tours", percentage: 10, amount: 3500, tip: "Guided tours, excursions.", icon: "map", color: "#68D391" },
          { name: "Attractions", percentage: 5, amount: 1750, tip: "Museums, parks, landmarks.", icon: "landmark", color: "#ECC94B" },
          { name: "Cultural Events", percentage: 5, amount: 1750, tip: "Festivals, concerts, local events.", icon: "music", color: "#B794F4" },
        ],
      },
      {
        name: "Daily Expenses",
        percentage: 15,
        amount: 5250,
        tip: "Food, groceries, and daily needs.",
        icon: "shopping-basket",
        color: "#38B2AC",
        subcategories: [
          { name: "Food", percentage: 10, amount: 3500, tip: "Groceries and dining out.", icon: "utensils", color: "#A0AEC0" },
          { name: "Miscellaneous", percentage: 5, amount: 1750, tip: "Souvenirs, toiletries, extras.", icon: "gift", color: "#F687B3" },
        ],
      },
    ],
    defaultAllocation: {
      "Transportation": 35,
      "Accommodation": 30,
      "Activities": 20,
      "Daily Expenses": 15,
    },
    recommendedIncome: {
      min: 30000,
      max: 100000,
    },
    timeline: "1 year (12 months)",
    tags: ["travel", "adventure", "lifestyle", "long-term"],
    color: "#63B3ED",
    icon: "globe",
    difficultyLevel: "in-progress",
  },
  // --- Career Sabbatical (Enhanced) ---
  {
    id: "sabbatical",
    name: "Career Sabbatical",
    description: "6-month career break planning",
    type: "50-30-20",
    categories: [
      {
        name: "Living Expenses",
        percentage: 50,
        amount: 15000,
        tip: "Rent, food, utilities during sabbatical.",
        icon: "home",
        color: "#ED8936",
        subcategories: [
          { name: "Housing", percentage: 30, amount: 9000, tip: "Rent or mortgage.", icon: "home", color: "#ED8936" },
          { name: "Utilities", percentage: 10, amount: 3000, tip: "Electricity, water, internet.", icon: "plug", color: "#63B3ED" },
          { name: "Food", percentage: 10, amount: 3000, tip: "Groceries and dining.", icon: "utensils", color: "#A0AEC0" },
        ],
      },
      {
        name: "Personal Development",
        percentage: 30,
        amount: 9000,
        tip: "Courses, certifications, books.",
        icon: "book-open",
        color: "#48BB78",
        subcategories: [
          { name: "Education", percentage: 15, amount: 4500, tip: "Online or in-person courses.", icon: "graduation-cap", color: "#4F8EF7" },
          { name: "Certifications", percentage: 10, amount: 3000, tip: "Professional certifications.", icon: "award", color: "#ECC94B" },
          { name: "Books & Resources", percentage: 5, amount: 1500, tip: "Books, online resources.", icon: "book", color: "#A0AEC0" },
        ],
      },
      {
        name: "Health & Wellness",
        percentage: 10,
        amount: 3000,
        tip: "Insurance, fitness, mental health.",
        icon: "heartbeat",
        color: "#E53E3E",
        subcategories: [
          { name: "Insurance", percentage: 5, amount: 1500, tip: "Health and travel insurance.", icon: "shield-alt", color: "#A0AEC0" },
          { name: "Fitness", percentage: 3, amount: 900, tip: "Gym, sports, fitness programs.", icon: "dumbbell", color: "#68D391" },
          { name: "Mental Health", percentage: 2, amount: 600, tip: "Therapy, counseling, meditation.", icon: "brain", color: "#B794F4" },
        ],
      },
      {
        name: "Emergency Fund",
        percentage: 10,
        amount: 3000,
        tip: "Unexpected sabbatical expenses.",
        icon: "exclamation-triangle",
        color: "#F56565",
      },
    ],
    defaultAllocation: {
      "Living Expenses": 50,
      "Personal Development": 30,
      "Health & Wellness": 10,
      "Emergency Fund": 10,
    },
    recommendedIncome: {
      min: 20000,
      max: 60000,
    },
    timeline: "6 months",
    tags: ["sabbatical", "career-break", "personal-development", "medium-term"],
    color: "#ED8936",
    icon: "coffee",
    difficultyLevel: "starter",
  },
  // --- Digital Nomad (Enhanced) ---
  {
    id: "digital-nomad",
    name: "Digital Nomad",
    description: "Remote work and travel lifestyle",
    type: "zero-based",
    categories: [
      {
        name: "Work Setup",
        percentage: 20,
        amount: 8000,
        tip: "Equipment, software, coworking spaces.",
        icon: "laptop-code",
        color: "#805AD5",
        subcategories: [
          { name: "Equipment", percentage: 10, amount: 4000, tip: "Laptop, phone, accessories.", icon: "laptop", color: "#805AD5" },
          { name: "Software", percentage: 5, amount: 2000, tip: "Productivity, security, office software.", icon: "code", color: "#68D391" },
          { name: "Coworking Spaces", percentage: 5, amount: 2000, tip: "Coworking memberships.", icon: "building", color: "#F6E05E" },
        ],
      },
      {
        name: "Living Expenses",
        percentage: 40,
        amount: 16000,
        tip: "Accommodation, food, utilities.",
        icon: "home",
        color: "#ED8936",
        subcategories: [
          { name: "Accommodation", percentage: 25, amount: 10000, tip: "Rentals, hostels, hotels.", icon: "bed", color: "#F6AD55" },
          { name: "Food", percentage: 10, amount: 4000, tip: "Groceries and dining.", icon: "utensils", color: "#A0AEC0" },
          { name: "Utilities", percentage: 5, amount: 2000, tip: "Electricity, water, internet.", icon: "plug", color: "#63B3ED" },
        ],
      },
      {
        name: "Travel",
        percentage: 25,
        amount: 10000,
        tip: "Flights, local transport, visas.",
        icon: "plane",
        color: "#63B3ED",
        subcategories: [
          { name: "Flights", percentage: 15, amount: 6000, tip: "International and domestic flights.", icon: "plane", color: "#63B3ED" },
          { name: "Local Transport", percentage: 5, amount: 2000, tip: "Buses, trains, taxis.", icon: "bus", color: "#F56565" },
          { name: "Visas", percentage: 5, amount: 2000, tip: "Visa fees and renewals.", icon: "passport", color: "#A0AEC0" },
        ],
      },
      {
        name: "Insurance & Healthcare",
        percentage: 15,
        amount: 6000,
        tip: "Health and travel insurance.",
        icon: "heartbeat",
        color: "#E53E3E",
        subcategories: [
          { name: "Health Insurance", percentage: 10, amount: 4000, tip: "Comprehensive health insurance.", icon: "heartbeat", color: "#E53E3E" },
          { name: "Travel Insurance", percentage: 5, amount: 2000, tip: "Travel insurance for emergencies.", icon: "shield-alt", color: "#A0AEC0" },
        ],
      },
    ],
    defaultAllocation: {
      "Work Setup": 20,
      "Living Expenses": 40,
      "Travel": 25,
      "Insurance & Healthcare": 15,
    },
    recommendedIncome: {
      min: 40000,
      max: 120000,
    },
    timeline: "1 year (12 months)",
    tags: ["digital-nomad", "remote-work", "travel", "lifestyle"],
    color: "#805AD5",
    icon: "laptop-code",
    difficultyLevel: "in-progress",
  },
  // --- Minimalist Living (New) ---
  {
    id: "minimalist-living",
    name: "Minimalist Living",
    description: "Simple, intentional living with reduced expenses.",
    type: "zero-based",
    categories: [
      {
        name: "Housing",
        percentage: 30,
        amount: 9000,
        tip: "Rent or mortgage for a small space.",
        icon: "home",
        color: "#ED8936",
      },
      {
        name: "Utilities & Bills",
        percentage: 15,
        amount: 4500,
        tip: "Electricity, water, internet, phone.",
        icon: "plug",
        color: "#63B3ED",
      },
      {
        name: "Food",
        percentage: 20,
        amount: 6000,
        tip: "Groceries, home-cooked meals.",
        icon: "utensils",
        color: "#A0AEC0",
      },
      {
        name: "Transportation",
        percentage: 10,
        amount: 3000,
        tip: "Public transport, bike, occasional car rental.",
        icon: "bus",
        color: "#F56565",
      },
      {
        name: "Experiences",
        percentage: 10,
        amount: 3000,
        tip: "Travel, hobbies, learning.",
        icon: "star",
        color: "#F6AD55",
      },
      {
        name: "Emergency Fund",
        percentage: 15,
        amount: 4500,
        tip: "Unexpected expenses.",
        icon: "exclamation-triangle",
        color: "#F56565",
      },
    ],
    defaultAllocation: {
      "Housing": 30,
      "Utilities & Bills": 15,
      "Food": 20,
      "Transportation": 10,
      "Experiences": 10,
      "Emergency Fund": 15,
    },
    recommendedIncome: {
      min: 20000,
      max: 50000,
    },
    timeline: "1 year (12 months)",
    tags: ["minimalism", "simple-living", "lifestyle", "budget"],
    color: "#A0AEC0",
    icon: "leaf",
    difficultyLevel: "starter",
  },
  // --- Fitness Transformation (New) ---
  {
    id: "fitness-transformation",
    name: "Fitness Transformation",
    description: "Budget for a year of fitness and health improvement.",
    type: "zero-based",
    categories: [
      {
        name: "Gym Membership",
        percentage: 25,
        amount: 1000,
        tip: "Annual gym or fitness club fees.",
        icon: "dumbbell",
        color: "#68D391",
      },
      {
        name: "Equipment & Gear",
        percentage: 20,
        amount: 800,
        tip: "Shoes, apparel, home equipment.",
        icon: "tshirt",
        color: "#805AD5",
      },
      {
        name: "Nutrition",
        percentage: 25,
        amount: 1000,
        tip: "Supplements, meal plans, groceries.",
        icon: "apple-alt",
        color: "#F6AD55",
      },
      {
        name: "Coaching & Classes",
        percentage: 20,
        amount: 800,
        tip: "Personal trainer, group classes.",
        icon: "user",
        color: "#F687B3",
      },
      {
        name: "Medical & Recovery",
        percentage: 10,
        amount: 400,
        tip: "Physical therapy, massage, checkups.",
        icon: "heartbeat",
        color: "#E53E3E",
      },
    ],
    defaultAllocation: {
      "Gym Membership": 25,
      "Equipment & Gear": 20,
      "Nutrition": 25,
      "Coaching & Classes": 20,
      "Medical & Recovery": 10,
    },
    recommendedIncome: {
      min: 2000,
      max: 5000,
    },
    timeline: "1 year (12 months)",
    tags: ["fitness", "health", "wellness", "lifestyle"],
    color: "#68D391",
    icon: "dumbbell",
    difficultyLevel: "starter",
  },
  // --- Sabbatical Abroad (New) ---
  {
    id: "sabbatical-abroad",
    name: "Sabbatical Abroad",
    description: "6-12 month sabbatical in a foreign country.",
    type: "zero-based",
    categories: [
      {
        name: "Travel & Visas",
        percentage: 25,
        amount: 5000,
        tip: "Flights, visas, travel insurance.",
        icon: "passport",
        color: "#63B3ED",
      },
      {
        name: "Accommodation",
        percentage: 30,
        amount: 6000,
        tip: "Rent, utilities, deposits.",
        icon: "bed",
        color: "#F6AD55",
      },
      {
        name: "Living Expenses",
        percentage: 25,
        amount: 5000,
        tip: "Food, transport, daily needs.",
        icon: "shopping-basket",
        color: "#38B2AC",
      },
      {
        name: "Language/Cultural Classes",
        percentage: 10,
        amount: 2000,
        tip: "Language school, cultural immersion.",
        icon: "globe",
        color: "#4F8EF7",
      },
      {
        name: "Emergency Fund",
        percentage: 10,
        amount: 2000,
        tip: "Unexpected expenses abroad.",
        icon: "exclamation-triangle",
        color: "#F56565",
      },
    ],
    defaultAllocation: {
      "Travel & Visas": 25,
      "Accommodation": 30,
      "Living Expenses": 25,
      "Language/Cultural Classes": 10,
      "Emergency Fund": 10,
    },
    recommendedIncome: {
      min: 15000,
      max: 35000,
    },
    timeline: "6-12 months",
    tags: ["sabbatical", "abroad", "travel", "lifestyle"],
    color: "#63B3ED",
    icon: "passport",
    difficultyLevel: "in-progress",
  },
  // --- Remote Work Move (New) ---
  {
    id: "remote-work-move",
    name: "Remote Work Move",
    description: "Budget for moving to a new city for remote work.",
    type: "zero-based",
    categories: [
      {
        name: "Moving Costs",
        percentage: 35,
        amount: 7000,
        tip: "Movers, truck rental, packing.",
        icon: "truck-moving",
        color: "#ED8936",
      },
      {
        name: "Home Office Setup",
        percentage: 20,
        amount: 4000,
        tip: "Desk, chair, monitor, internet setup.",
        icon: "laptop-code",
        color: "#805AD5",
      },
      {
        name: "Rent & Deposits",
        percentage: 25,
        amount: 5000,
        tip: "First month, deposit, utilities setup.",
        icon: "home",
        color: "#ED8936",
      },
      {
        name: "Exploration & Social",
        percentage: 10,
        amount: 2000,
        tip: "Getting to know your new city.",
        icon: "users",
        color: "#F687B3",
      },
      {
        name: "Emergency Fund",
        percentage: 10,
        amount: 2000,
        tip: "Unexpected moving expenses.",
        icon: "exclamation-triangle",
        color: "#F56565",
      },
    ],
    defaultAllocation: {
      "Moving Costs": 35,
      "Home Office Setup": 20,
      "Rent & Deposits": 25,
      "Exploration & Social": 10,
      "Emergency Fund": 10,
    },
    recommendedIncome: {
      min: 15000,
      max: 50000,
    },
    timeline: "6 months",
    tags: ["remote-work", "move", "lifestyle", "city"],
    color: "#ED8936",
    icon: "laptop-code",
    difficultyLevel: "starter",
  },
  // --- Luxury Vacation (New) ---
  {
    id: "luxury-vacation",
    name: "Luxury Vacation",
    description: "Budget for a 2-week high-end vacation.",
    type: "zero-based",
    categories: [
      {
        name: "Flights (Business/First)",
        percentage: 30,
        amount: 6000,
        tip: "Premium airfare for comfort.",
        icon: "plane",
        color: "#63B3ED",
      },
      {
        name: "Luxury Accommodation",
        percentage: 30,
        amount: 6000,
        tip: "5-star hotels, resorts, villas.",
        icon: "bed",
        color: "#F6AD55",
      },
      {
        name: "Fine Dining",
        percentage: 15,
        amount: 3000,
        tip: "Gourmet meals and experiences.",
        icon: "utensils",
        color: "#A0AEC0",
      },
      {
        name: "Exclusive Activities",
        percentage: 15,
        amount: 3000,
        tip: "Private tours, spa, golf, events.",
        icon: "star",
        color: "#F6AD55",
      },
      {
        name: "Shopping & Souvenirs",
        percentage: 5,
        amount: 1000,
        tip: "Luxury shopping, gifts.",
        icon: "shopping-bag",
        color: "#ECC94B",
      },
      {
        name: "Emergency Fund",
        percentage: 5,
        amount: 1000,
        tip: "Unexpected vacation expenses.",
        icon: "exclamation-triangle",
        color: "#F56565",
      },
    ],
    defaultAllocation: {
      "Flights (Business/First)": 30,
      "Luxury Accommodation": 30,
      "Fine Dining": 15,
      "Exclusive Activities": 15,
      "Shopping & Souvenirs": 5,
      "Emergency Fund": 5,
    },
    recommendedIncome: {
      min: 15000,
      max: 50000,
    },
    timeline: "2 weeks",
    tags: ["luxury", "vacation", "travel", "lifestyle"],
    color: "#F6AD55",
    icon: "star",
    difficultyLevel: "advanced",
  },
  {
    id: "world-travel",
    name: "World Travel",
    description: "12-month world travel budget",
    type: "zero-based",
    categories: [
      {
        name: "Transportation",
        percentage: 35,
        amount: 0,
        subcategories: [
          { name: "Flights", percentage: 20, amount: 0 },
          { name: "Local Transport", percentage: 10, amount: 0 },
          { name: "Travel Insurance", percentage: 5, amount: 0 },
        ],
      },
      {
        name: "Accommodation",
        percentage: 30,
        amount: 0,
        subcategories: [
          { name: "Hotels", percentage: 15, amount: 0 },
          { name: "Hostels", percentage: 10, amount: 0 },
          { name: "Airbnb", percentage: 5, amount: 0 },
        ],
      },
      {
        name: "Activities",
        percentage: 20,
        amount: 0,
        subcategories: [
          { name: "Tours", percentage: 10, amount: 0 },
          { name: "Attractions", percentage: 5, amount: 0 },
          { name: "Cultural Events", percentage: 5, amount: 0 },
        ],
      },
      {
        name: "Daily Expenses",
        percentage: 15,
        amount: 0,
        subcategories: [
          { name: "Food", percentage: 10, amount: 0 },
          { name: "Miscellaneous", percentage: 5, amount: 0 },
        ],
      },
    ],
    defaultAllocation: {
      "Transportation": 35,
      "Accommodation": 30,
      "Activities": 20,
      "Daily Expenses": 15,
    },
    recommendedIncome: {
      min: 30000,
      max: 100000,
    },
    timeline: "12 months",
    tags: ["travel", "adventure", "lifestyle"],
  },
  {
    id: "sabbatical",
    name: "Career Sabbatical",
    description: "6-month career break planning",
    type: "50-30-20",
    categories: [
      {
        name: "Living Expenses",
        percentage: 50,
        amount: 0,
        subcategories: [
          { name: "Housing", percentage: 30, amount: 0 },
          { name: "Utilities", percentage: 10, amount: 0 },
          { name: "Food", percentage: 10, amount: 0 },
        ],
      },
      {
        name: "Personal Development",
        percentage: 30,
        amount: 0,
        subcategories: [
          { name: "Education", percentage: 15, amount: 0 },
          { name: "Certifications", percentage: 10, amount: 0 },
          { name: "Books & Resources", percentage: 5, amount: 0 },
        ],
      },
      {
        name: "Health & Wellness",
        percentage: 10,
        amount: 0,
        subcategories: [
          { name: "Insurance", percentage: 5, amount: 0 },
          { name: "Fitness", percentage: 3, amount: 0 },
          { name: "Mental Health", percentage: 2, amount: 0 },
        ],
      },
      {
        name: "Emergency Fund",
        percentage: 10,
        amount: 0,
      },
    ],
    defaultAllocation: {
      "Living Expenses": 50,
      "Personal Development": 30,
      "Health & Wellness": 10,
      "Emergency Fund": 10,
    },
    recommendedIncome: {
      min: 20000,
      max: 60000,
    },
    timeline: "6 months",
    tags: ["sabbatical", "career-break", "personal-development"],
  },
  {
    id: "digital-nomad",
    name: "Digital Nomad",
    description: "Remote work and travel lifestyle",
    type: "zero-based",
    categories: [
      {
        name: "Work Setup",
        percentage: 20,
        amount: 0,
        subcategories: [
          { name: "Equipment", percentage: 10, amount: 0 },
          { name: "Software", percentage: 5, amount: 0 },
          { name: "Coworking Spaces", percentage: 5, amount: 0 },
        ],
      },
      {
        name: "Living Expenses",
        percentage: 40,
        amount: 0,
        subcategories: [
          { name: "Accommodation", percentage: 25, amount: 0 },
          { name: "Food", percentage: 10, amount: 0 },
          { name: "Utilities", percentage: 5, amount: 0 },
        ],
      },
      {
        name: "Travel",
        percentage: 25,
        amount: 0,
        subcategories: [
          { name: "Flights", percentage: 15, amount: 0 },
          { name: "Local Transport", percentage: 5, amount: 0 },
          { name: "Visas", percentage: 5, amount: 0 },
        ],
      },
      {
        name: "Insurance & Healthcare",
        percentage: 15,
        amount: 0,
        subcategories: [
          { name: "Health Insurance", percentage: 10, amount: 0 },
          { name: "Travel Insurance", percentage: 5, amount: 0 },
        ],
      },
    ],
    defaultAllocation: {
      "Work Setup": 20,
      "Living Expenses": 40,
      "Travel": 25,
      "Insurance & Healthcare": 15,
    },
    recommendedIncome: {
      min: 40000,
      max: 120000,
    },
    timeline: "12 months",
    tags: ["digital-nomad", "remote-work", "travel"],
  },
]
