import type { BudgetTemplate } from "@/types/budget"

export const LIFE_EVENT_TEMPLATES: BudgetTemplate[] = [
  // --- College Education (Enhanced) ---
  {
    id: "college",
    name: "College Education",
    description: "4-year college education budget planning",
    type: "zero-based",
    categories: [
      {
        name: "Tuition & Fees",
        percentage: 60,
        amount: 54000,
        tip: "Include tuition, lab fees, and registration costs.",
        icon: "graduation-cap",
        color: "#4F8EF7",
        subcategories: [
          { name: "Tuition", percentage: 50, amount: 45000, tip: "Annual tuition for 4 years.", icon: "university", color: "#5A67D8" },
          { name: "Student Fees", percentage: 5, amount: 4500, tip: "Student activity and technology fees.", icon: "file-invoice-dollar", color: "#ECC94B" },
          { name: "Books & Supplies", percentage: 5, amount: 4500, tip: "Textbooks, notebooks, and supplies.", icon: "book-open", color: "#48BB78" },
        ],
      },
      {
        name: "Housing",
        percentage: 25,
        amount: 22500,
        tip: "Dorms, rent, or off-campus housing.",
        icon: "home",
        color: "#ED8936",
        subcategories: [
          { name: "Room & Board", percentage: 20, amount: 18000, tip: "On/off-campus living costs.", icon: "bed", color: "#F6AD55" },
          { name: "Utilities", percentage: 5, amount: 4500, tip: "Electricity, water, internet.", icon: "plug", color: "#63B3ED" },
        ],
      },
      {
        name: "Living Expenses",
        percentage: 10,
        amount: 9000,
        tip: "Daily living and transportation.",
        icon: "shopping-cart",
        color: "#38B2AC",
        subcategories: [
          { name: "Food", percentage: 5, amount: 4500, tip: "Groceries and dining out.", icon: "utensils", color: "#A0AEC0" },
          { name: "Transportation", percentage: 3, amount: 2700, tip: "Bus, car, bike, or ride-share.", icon: "bus", color: "#F56565" },
          { name: "Personal Care", percentage: 2, amount: 1800, tip: "Clothing, toiletries, laundry.", icon: "user", color: "#B794F4" },
        ],
      },
      {
        name: "Emergency Fund",
        percentage: 5,
        amount: 4500,
        tip: "Unexpected expenses or emergencies.",
        icon: "exclamation-triangle",
        color: "#F56565",
      },
    ],
    defaultAllocation: {
      "Tuition & Fees": 60,
      "Housing": 25,
      "Living Expenses": 10,
      "Emergency Fund": 5,
    },
    recommendedIncome: {
      min: 80000,
      max: 200000,
    },
    timeline: "4 years (48 months)",
    tags: ["education", "college", "long-term", "starter"],
    color: "#4F8EF7",
    icon: "graduation-cap",
    difficultyLevel: "starter",
  },
  // --- Early Retirement (Enhanced) ---
  {
    id: "retirement",
    name: "Early Retirement",
    description: "FIRE (Financial Independence, Retire Early) planning",
    type: "50-30-20",
    categories: [
      {
        name: "Investment Portfolio",
        percentage: 50,
        amount: 150000,
        tip: "Stocks, bonds, and real estate investments.",
        icon: "chart-line",
        color: "#68D391",
        subcategories: [
          { name: "Index Funds", percentage: 30, amount: 90000, tip: "Broad market index funds.", icon: "chart-pie", color: "#4299E1" },
          { name: "Real Estate", percentage: 15, amount: 45000, tip: "Rental or investment properties.", icon: "home", color: "#ED8936" },
          { name: "Bonds", percentage: 5, amount: 15000, tip: "Government or corporate bonds.", icon: "file-invoice", color: "#A0AEC0" },
        ],
      },
      {
        name: "Debt Elimination",
        percentage: 20,
        amount: 60000,
        tip: "Pay off mortgage and other debts.",
        icon: "credit-card",
        color: "#F56565",
        subcategories: [
          { name: "Mortgage", percentage: 15, amount: 45000, tip: "Home mortgage principal.", icon: "home", color: "#ED8936" },
          { name: "Other Debts", percentage: 5, amount: 15000, tip: "Car loans, credit cards, etc.", icon: "credit-card", color: "#F56565" },
        ],
      },
      {
        name: "Living Expenses",
        percentage: 20,
        amount: 60000,
        tip: "Day-to-day living, housing, food.",
        icon: "shopping-bag",
        color: "#ECC94B",
        subcategories: [
          { name: "Housing", percentage: 10, amount: 30000, tip: "Rent or property taxes.", icon: "home", color: "#ED8936" },
          { name: "Utilities", percentage: 5, amount: 15000, tip: "Electricity, water, gas.", icon: "plug", color: "#63B3ED" },
          { name: "Food", percentage: 5, amount: 15000, tip: "Groceries and dining.", icon: "utensils", color: "#A0AEC0" },
        ],
      },
      {
        name: "Healthcare Fund",
        percentage: 10,
        amount: 30000,
        tip: "Medical insurance and out-of-pocket costs.",
        icon: "heartbeat",
        color: "#E53E3E",
      },
    ],
    defaultAllocation: {
      "Investment Portfolio": 50,
      "Debt Elimination": 20,
      "Living Expenses": 20,
      "Healthcare Fund": 10,
    },
    recommendedIncome: {
      min: 100000,
      max: 500000,
    },
    timeline: "10 years (120 months)",
    tags: ["retirement", "investment", "long-term", "advanced"],
    color: "#68D391",
    icon: "chart-line",
    difficultyLevel: "advanced",
  },
  // --- Business Startup (Enhanced) ---
  {
    id: "business-startup",
    name: "Business Startup",
    description: "First-year business launch budget",
    type: "zero-based",
    categories: [
      {
        name: "Startup Costs",
        percentage: 40,
        amount: 60000,
        tip: "Legal, licenses, and initial inventory.",
        icon: "briefcase",
        color: "#805AD5",
        subcategories: [
          { name: "Legal & Licenses", percentage: 10, amount: 15000, tip: "Business registration, legal fees.", icon: "file-signature", color: "#ECC94B" },
          { name: "Equipment", percentage: 20, amount: 30000, tip: "Machinery, computers, office setup.", icon: "tools", color: "#68D391" },
          { name: "Initial Inventory", percentage: 10, amount: 15000, tip: "First stock purchase.", icon: "boxes", color: "#F6AD55" },
        ],
      },
      {
        name: "Operating Expenses",
        percentage: 30,
        amount: 45000,
        tip: "Rent, utilities, insurance, supplies.",
        icon: "building",
        color: "#F6E05E",
        subcategories: [
          { name: "Rent", percentage: 15, amount: 22500, tip: "Office or retail rent.", icon: "home", color: "#ED8936" },
          { name: "Utilities", percentage: 5, amount: 7500, tip: "Electricity, water, internet.", icon: "plug", color: "#63B3ED" },
          { name: "Insurance", percentage: 5, amount: 7500, tip: "Business insurance.", icon: "shield-alt", color: "#A0AEC0" },
          { name: "Supplies", percentage: 5, amount: 7500, tip: "Office or store supplies.", icon: "shopping-basket", color: "#38B2AC" },
        ],
      },
      {
        name: "Marketing",
        percentage: 15,
        amount: 22500,
        tip: "Advertising and website costs.",
        icon: "bullhorn",
        color: "#F687B3",
        subcategories: [
          { name: "Advertising", percentage: 10, amount: 15000, tip: "Online and offline ads.", icon: "ad", color: "#F56565" },
          { name: "Website", percentage: 5, amount: 7500, tip: "Domain, hosting, web development.", icon: "globe", color: "#4299E1" },
        ],
      },
      {
        name: "Working Capital",
        percentage: 15,
        amount: 22500,
        tip: "Cash for operations and emergencies.",
        icon: "wallet",
        color: "#48BB78",
      },
    ],
    defaultAllocation: {
      "Startup Costs": 40,
      "Operating Expenses": 30,
      "Marketing": 15,
      "Working Capital": 15,
    },
    recommendedIncome: {
      min: 50000,
      max: 250000,
    },
    timeline: "1 year (12 months)",
    tags: ["business", "startup", "entrepreneurship", "short-term"],
    color: "#805AD5",
    icon: "briefcase",
    difficultyLevel: "in-progress",
  },
  // --- Debt Freedom (Enhanced) ---
  {
    id: "debt-freedom",
    name: "Debt Freedom",
    description: "Debt snowball/avalanche strategy",
    type: "zero-based",
    categories: [
      {
        name: "High Interest Debt",
        percentage: 50,
        amount: 25000,
        tip: "Focus on paying off high-interest debts first.",
        icon: "credit-card",
        color: "#E53E3E",
        subcategories: [
          { name: "Credit Cards", percentage: 30, amount: 15000, tip: "All credit card balances.", icon: "credit-card", color: "#F56565" },
          { name: "Personal Loans", percentage: 20, amount: 10000, tip: "Unsecured personal loans.", icon: "money-bill", color: "#38B2AC" },
        ],
      },
      {
        name: "Medium Interest Debt",
        percentage: 30,
        amount: 15000,
        tip: "Car loans, student loans, etc.",
        icon: "car",
        color: "#F6AD55",
        subcategories: [
          { name: "Car Loans", percentage: 20, amount: 10000, tip: "Auto loans.", icon: "car", color: "#F6AD55" },
          { name: "Student Loans", percentage: 10, amount: 5000, tip: "Student loan balances.", icon: "graduation-cap", color: "#4F8EF7" },
        ],
      },
      {
        name: "Low Interest Debt",
        percentage: 10,
        amount: 5000,
        tip: "Mortgage or other low-rate loans.",
        icon: "home",
        color: "#68D391",
        subcategories: [
          { name: "Mortgage", percentage: 10, amount: 5000, tip: "Home mortgage.", icon: "home", color: "#ED8936" },
        ],
      },
      {
        name: "Emergency Fund",
        percentage: 10,
        amount: 5000,
        tip: "Buffer for unexpected expenses.",
        icon: "exclamation-triangle",
        color: "#F56565",
      },
    ],
    defaultAllocation: {
      "High Interest Debt": 50,
      "Medium Interest Debt": 30,
      "Low Interest Debt": 10,
      "Emergency Fund": 10,
    },
    recommendedIncome: {
      min: 40000,
      max: 150000,
    },
    timeline: "3 years (36 months)",
    tags: ["debt", "financial-freedom", "snowball", "starter"],
    color: "#E53E3E",
    icon: "credit-card",
    difficultyLevel: "starter",
  },
  // --- Wedding (New) ---
  {
    id: "wedding",
    name: "Wedding",
    description: "Comprehensive wedding budget for a mid-size event.",
    type: "zero-based",
    categories: [
      {
        name: "Venue & Catering",
        percentage: 40,
        amount: 12000,
        tip: "Venue rental, food, and drinks.",
        icon: "glass-cheers",
        color: "#F687B3",
        subcategories: [
          { name: "Venue", percentage: 25, amount: 7500, tip: "Ceremony and reception location.", icon: "building", color: "#F6E05E" },
          { name: "Catering", percentage: 15, amount: 4500, tip: "Food and beverage costs.", icon: "utensils", color: "#A0AEC0" },
        ],
      },
      {
        name: "Attire & Beauty",
        percentage: 15,
        amount: 4500,
        tip: "Wedding dress, suits, hair, and makeup.",
        icon: "user-tie",
        color: "#805AD5",
      },
      {
        name: "Photography & Entertainment",
        percentage: 15,
        amount: 4500,
        tip: "Photographer, videographer, DJ/band.",
        icon: "camera",
        color: "#68D391",
      },
      {
        name: "Decor & Flowers",
        percentage: 10,
        amount: 3000,
        tip: "Decorations, floral arrangements.",
        icon: "flower",
        color: "#F6AD55",
      },
      {
        name: "Rings & Licenses",
        percentage: 10,
        amount: 3000,
        tip: "Wedding rings, marriage license.",
        icon: "ring",
        color: "#ECC94B",
      },
      {
        name: "Miscellaneous",
        percentage: 10,
        amount: 3000,
        tip: "Invitations, transportation, gifts, etc.",
        icon: "gift",
        color: "#38B2AC",
      },
    ],
    defaultAllocation: {
      "Venue & Catering": 40,
      "Attire & Beauty": 15,
      "Photography & Entertainment": 15,
      "Decor & Flowers": 10,
      "Rings & Licenses": 10,
      "Miscellaneous": 10,
    },
    recommendedIncome: {
      min: 20000,
      max: 50000,
    },
    timeline: "1 year (12 months)",
    tags: ["wedding", "event", "short-term", "family"],
    color: "#F687B3",
    icon: "glass-cheers",
    difficultyLevel: "starter",
  },
  // --- First Home Purchase (New) ---
  {
    id: "first-home",
    name: "First Home Purchase",
    description: "Budget for buying your first home.",
    type: "zero-based",
    categories: [
      {
        name: "Down Payment",
        percentage: 50,
        amount: 50000,
        tip: "Initial payment on the home.",
        icon: "home",
        color: "#4F8EF7",
      },
      {
        name: "Closing Costs",
        percentage: 10,
        amount: 10000,
        tip: "Fees for completing the purchase.",
        icon: "file-invoice-dollar",
        color: "#ECC94B",
      },
      {
        name: "Moving & Setup",
        percentage: 10,
        amount: 10000,
        tip: "Moving company, initial setup, furniture.",
        icon: "truck-moving",
        color: "#ED8936",
      },
      {
        name: "Emergency Fund",
        percentage: 10,
        amount: 10000,
        tip: "Unexpected home expenses.",
        icon: "exclamation-triangle",
        color: "#F56565",
      },
      {
        name: "Initial Repairs & Improvements",
        percentage: 20,
        amount: 20000,
        tip: "Renovations, painting, repairs.",
        icon: "tools",
        color: "#805AD5",
      },
    ],
    defaultAllocation: {
      "Down Payment": 50,
      "Closing Costs": 10,
      "Moving & Setup": 10,
      "Emergency Fund": 10,
      "Initial Repairs & Improvements": 20,
    },
    recommendedIncome: {
      min: 60000,
      max: 200000,
    },
    timeline: "1 year (12 months)",
    tags: ["home", "real-estate", "purchase", "short-term"],
    color: "#4F8EF7",
    icon: "home",
    difficultyLevel: "starter",
  },
  // --- Relocation (New) ---
  {
    id: "relocation",
    name: "Relocation",
    description: "Budget for moving to a new city or country.",
    type: "zero-based",
    categories: [
      {
        name: "Moving Company",
        percentage: 30,
        amount: 6000,
        tip: "Professional movers or truck rental.",
        icon: "truck-moving",
        color: "#ED8936",
      },
      {
        name: "Travel",
        percentage: 20,
        amount: 4000,
        tip: "Flights, gas, or other travel.",
        icon: "plane",
        color: "#63B3ED",
      },
      {
        name: "Temporary Housing",
        percentage: 20,
        amount: 4000,
        tip: "Hotel or short-term rental.",
        icon: "bed",
        color: "#F6AD55",
      },
      {
        name: "Deposits & Fees",
        percentage: 10,
        amount: 2000,
        tip: "Rental deposits, utility setup.",
        icon: "file-invoice-dollar",
        color: "#ECC94B",
      },
      {
        name: "Miscellaneous",
        percentage: 20,
        amount: 4000,
        tip: "Packing, insurance, meals, etc.",
        icon: "boxes",
        color: "#48BB78",
      },
    ],
    defaultAllocation: {
      "Moving Company": 30,
      "Travel": 20,
      "Temporary Housing": 20,
      "Deposits & Fees": 10,
      "Miscellaneous": 20,
    },
    recommendedIncome: {
      min: 20000,
      max: 100000,
    },
    timeline: "6 months",
    tags: ["relocation", "move", "short-term", "life-event"],
    color: "#ED8936",
    icon: "truck-moving",
    difficultyLevel: "starter",
  },
  // --- Family Expansion (New) ---
  {
    id: "family-expansion",
    name: "Family Expansion",
    description: "Budget for having a baby or adopting a child.",
    type: "zero-based",
    categories: [
      {
        name: "Medical & Delivery",
        percentage: 35,
        amount: 10500,
        tip: "Prenatal care, hospital, delivery.",
        icon: "heartbeat",
        color: "#E53E3E",
      },
      {
        name: "Baby Supplies",
        percentage: 25,
        amount: 7500,
        tip: "Clothes, crib, stroller, diapers.",
        icon: "baby",
        color: "#F6E05E",
      },
      {
        name: "Childcare",
        percentage: 20,
        amount: 6000,
        tip: "Daycare, babysitter, or nanny.",
        icon: "user-nurse",
        color: "#805AD5",
      },
      {
        name: "Parental Leave Income Gap",
        percentage: 10,
        amount: 3000,
        tip: "Lost income during leave.",
        icon: "calendar-minus",
        color: "#ECC94B",
      },
      {
        name: "Emergency Fund",
        percentage: 10,
        amount: 3000,
        tip: "Unexpected baby expenses.",
        icon: "exclamation-triangle",
        color: "#F56565",
      },
    ],
    defaultAllocation: {
      "Medical & Delivery": 35,
      "Baby Supplies": 25,
      "Childcare": 20,
      "Parental Leave Income Gap": 10,
      "Emergency Fund": 10,
    },
    recommendedIncome: {
      min: 30000,
      max: 100000,
    },
    timeline: "1 year (12 months)",
    tags: ["family", "baby", "adoption", "life-event"],
    color: "#E53E3E",
    icon: "baby",
    difficultyLevel: "starter",
  },
  // --- Gap Year (New) ---
  {
    id: "gap-year",
    name: "Gap Year",
    description: "Budget for taking a year off for travel, volunteering, or study.",
    type: "zero-based",
    categories: [
      {
        name: "Travel",
        percentage: 40,
        amount: 12000,
        tip: "Flights, local transport, visas.",
        icon: "plane",
        color: "#63B3ED",
      },
      {
        name: "Accommodation",
        percentage: 25,
        amount: 7500,
        tip: "Hostels, hotels, or rentals.",
        icon: "bed",
        color: "#F6AD55",
      },
      {
        name: "Food & Daily Expenses",
        percentage: 20,
        amount: 6000,
        tip: "Groceries, restaurants, daily needs.",
        icon: "utensils",
        color: "#A0AEC0",
      },
      {
        name: "Volunteering/Programs",
        percentage: 10,
        amount: 3000,
        tip: "Program fees, donations, supplies.",
        icon: "hands-helping",
        color: "#68D391",
      },
      {
        name: "Emergency Fund",
        percentage: 5,
        amount: 1500,
        tip: "Unexpected costs while abroad.",
        icon: "exclamation-triangle",
        color: "#F56565",
      },
    ],
    defaultAllocation: {
      "Travel": 40,
      "Accommodation": 25,
      "Food & Daily Expenses": 20,
      "Volunteering/Programs": 10,
      "Emergency Fund": 5,
    },
    recommendedIncome: {
      min: 15000,
      max: 50000,
    },
    timeline: "1 year (12 months)",
    tags: ["gap-year", "travel", "volunteering", "study", "adventure"],
    color: "#63B3ED",
    icon: "plane",
    difficultyLevel: "starter",
  },





]
